#!/bin/bash

# Create Docker image used to create build within
export IMAGE_NAME=ubuntu_20_yocto_openvino
if [ -z $(docker images -q $IMAGE_NAME) ]; then
   echo "Building image ..."
   docker build -t $IMAGE_NAME docker	
fi

# Build workspace
docker run --rm -it -v `pwd`:`pwd` -w `pwd` -e CI_SOURCE_PATH=`pwd` -t $IMAGE_NAME /bin/bash _build

#sudo qemu-system-x86_64 \
  -cpu host \
  -enable-kvm \
  -m 16G \
  -smp cores=8,sockets=1,threads=1 \
  -rtc base=localtime \
  -kernel build/tmp/deploy/images/qemux86-64/bzImage \
  -drive file=build/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64.rootfs.ext4,format=raw \
  -append "root=/dev/sda rw"
